### PR TITLE
Test out of tree

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by czgdp1807** [comment]
Thanks @certik and @Smit-create for taking the initiative on this. ❤️🚀. Its an important one.

**Comment by certik** [comment]
@Smit-create go ahead and try to finish it, I have to work on other things.

**Comment by Smit-create** [comment]
Ah, windows still fail. Mac and Linux are happy. May be some issues with `<filesystem>`?

**Comment by certik** [comment]
The windows error is:
```
D:\a\lpython\lpython\lpython-0.2.0-1053-g577343ea8\src\lpython\semantics\python_ast_to_asr.cpp(3607): error C2664: 'LFortran::Result<LFortran::ASR::asr_t *> LFortran::LPython::symbol_table_visitor(Allocator &,const LFortran::LPython::AST::Module_t &,LFortran::diag::Diagnostics &,bool,std::map<int,LFortran::ASR::symbol_t *,std::less<int>,std::allocator<std::pair<const int,LFortran::ASR::symbol_t *>>> &,std::string)': cannot convert argument 6 from 'std::filesystem::path' to 'std::string'

```

**Comment by czgdp1807** [comment]
Works locally as expected.

**Review by czgdp1807 — APPROVED** [review]

**Comment by Smit-create** [comment]
@certik Please take a look.

**Comment by certik** [comment]
It seems to work for me, so I am going to go ahead and merge this. Thanks!

**Comment by certik** [comment]
This PR breaks the build on gcc 7.5.0.
