### ISSUE TITLE
Bug in LPython 0.19.0 emulation mode: 'function' object has no attribute 'restype'

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2222]
It works with LPython 0.18.4, but breaks with LPython 0.19.0:
```
  File "/root/mambaforge/envs/ch_emulation/share/lpython/lib/lpython/lpython.py", line 398, in __call__
    if self.cf.restype == ctypes.c_char_p:
AttributeError: 'function' object has no attribute 'restype'
```
I still need to create a minimal example.

**Comment by certik** [comment]
This fixes it:
```diff
diff --git a/src/runtime/lpython/lpython.py b/src/runtime/lpython/lpython.py
index 2f0eee0b5..1f09e9abb 100644
--- a/src/runtime/lpython/lpython.py
+++ b/src/runtime/lpython/lpython.py
@@ -371,6 +371,7 @@ class CTypes:
             self.cf = self.library[self.name]
         else:
             self.cf = CTypes.emulations[self.name]
+            self.cf.restype = None
         argtypes = []
         for arg in self.args:
             arg_type = self.annotations[arg]
```

**Comment by certik** [comment]
This change was introduced in https://github.com/lcompilers/lpython/pull/2196.
